name: Build, Test & SonarCloud Analysis

on:
  push:
    branches: [main]

jobs:
  build:
    name: Run Tests and SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build, test and generate coverage
        run: ./gradlew clean build jacocoTestReport

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar -Dsonar.token=$SONAR_TOKEN

      - name: Upload Gradle Problems Report
        if: always() # Executa mesmo que o build ou análise falhem
        uses: actions/upload-artifact@v4
        with:
          name: gradle-problems-report
          path: build/reports/problems/problems-report.html
      
      - name: Export SonarCloud JSON Reports
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PROJECT_KEY: MarioOctavio_algashop-ordering # substitua aqui
        run: |
          mkdir -p sonar-report

          curl -u "$SONAR_TOKEN:" "https://sonarcloud.io/api/measures/component?component=$PROJECT_KEY&metricKeys=bugs,vulnerabilities,code_smells,coverage,duplicated_lines_density,ncloc" \
            -o sonar-report/measures.json

          curl -u "$SONAR_TOKEN:" "https://sonarcloud.io/api/issues/search?componentKeys=$PROJECT_KEY&ps=500" \
            -o sonar-report/issues.json

          curl -u "$SONAR_TOKEN:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECT_KEY" \
            -o sonar-report/quality_gate.json
            
      - name: Upload SonarCloud Report
        uses: actions/upload-artifact@v4
        with:
          name: sonarcloud-report
          path: sonar-report/

